### ISSUE TITLE
Long Movie names are not shown properly

### ISSUE THREAD

**Issue by lazyjinchuriki** [MoviebaseApp/tmdb-kotlin#110]
In the Moviebase app some movie names like "Batman: The doom that came to Gotham" only shows "Batman: The doom that came to". I'm sure it is done to prevent text from overflowing and wrecking the overall structure, but i think it can easily be fixed with little to no efforts.
![Screenshot_20230830_113952_Moviebase](https://github.com/MoviebaseApp/tmdb-kotlin/assets/92175633/e16e1851-f924-4d68-af02-d85a715f2b86)

**Comment by chrisnkrueger** [comment]
Thanks for the bug report.
