### ISSUE TITLE
How to Fetch Alternative Titles?

### ISSUE THREAD

**Issue by ARSOFT1** [MoviebaseApp/tmdb-kotlin#126]
**Library Version:** 1.2.0

**Description:**
I am trying to fetch alternative titles for movies or shows. I've looked at the code, but I couldn't find information on how to achieve this. Can someone provide guidance to retrieve alternative titles? While I can see on TMDB Documentation API of Alternative Titles ==> https://api.themoviedb.org/3/movie/550/alternative_titles?api_key=""

**Comment by chrisnkrueger** [comment]
You can create a new instance Tmdb3().movie.getDetails(), the response should have the alternative titles.
Check the doc here https://developer.themoviedb.org/reference/intro/getting-started
