### ISSUE TITLE
Add support for endpoints

### ISSUE THREAD

**Issue by chrisnkrueger** [MoviebaseApp/tmdb-kotlin#30]
Add the model and add the endpoints for:

- [ ] TmdbCertificationsApi
- [ ] TmdbChangesApi
- [ ] TmdbCreditsApi
- [ ] TmdbGenresApi
- [ ] TmdbGuestSessionsApi
- [ ] TmdbKeywordsApi
- [ ] TmdbListsApi
- [ ] TmdbReviewsApi
- [ ] TmdbShowEpisodeGroupsApi

**Comment by Rattlyy** [comment]
is this abandoned?

**Comment by chrisnkrueger** [comment]
No, I am still working on the API.
